DATASET:
  ROOT : /home/palnak/Dataset/temp
  EXP_NAME : INRIA_REFINE_LITE
  NORMALIZATION : divide_by_255
  TRANSFORMATION:
    DualCompose:
      transform_1:
        augment_prob: 0.6
        to_perform:
          - HorizontalFlip
        transform_type: OneOf

MODEL:
  MODEL_NAME: BinaryNetwork
  MODEL_PARAM:



TRAIN:
  IMAGE_DIM: [64, 64]
  EPOCH: 2
  BATCH: 1
  ML_TYPE : binary

  LOSS:
    NAME: Jaccard
    PARAM:
      jaccard_weight: 0.3

  SCHEDULER:
    NAME: PolyLrDecay
    PARAM:
      power: 0.9
      max_epochs: 2

  OPTIMIZER:
    NAME: Adam
    PARAM:
      lr: 0.0001
