DLinkNet34:
  num_classes: 2
  pre_trained_image_net: true
  res_net_to_use: resnet34
Date: 05-01-2020
JaccardBinaryLoss:
  jaccard_weight: 1
PolyLrDecay:
  decay_after_epoch: 1
  max_epochs: 20
  power: 0.9
RMSprop:
  alpha: 0.995
  lr: 0.001
  momentum: 0
  weight_decay: 0
Status: DEFAULT
Version: v1
early_stopping:
  min_delta: 0
  patience: 4
experiment_name: testbob1
initial_assignment:
  batch_size: 2
  model_input_dimension:
  - 512
  - 512
  n_epochs: 20
loss: JaccardBinaryLoss
model: DLinkNet34
normalization: DivideBy255
optimizer: RMSprop
problem_type: super_resolution
root: /home/palnak/Dataset/scratch_inria
scheduler: PolyLrDecay
training_state: DEFAULT
transfer_weights_path: null
transformation:
  DualCompose:
    transform_1:
      augment_prob: 0.5
      to_perform:
      - HorizontalFlip
      - VerticalFlip
      - RandomFilter
      transform_type: OneOf
