root : /home/palnak/Dataset/scratch_inria
experiment_name : INRIA_HIGH_RESO
problem_type : binary

initial_assignment:
  model_input_dimension: [384, 384]
  n_epochs: 150
  batch_size: 4


transformation :
  DualCompose:
    transform_1:
      to_perform:
        - HorizontalFlip
        - VerticalFlip
        - Rotate
        - MirrorCrop
        - RescaleCrop
        - RandomFilter
        - RandomBrightness
        - RandomContrast
        - CLAHE
      transform_type: OneOf
      augment_prob: 0.5

normalization : Normalize