model:
  BuildingBoundaryRefineNetExtractor:
    backbone_to_use: resnet34
    top_layers_trainable: True
    classes: 2
    pre_trained_image_net: True
    final_mode: bilinear


loss:
  BuildingBoundarySigmoidLoss:
    building_weight: 1
    boundary_weight: 1

scheduler :
  PolyLrDecay:
    decay_after_epoch: 1
    power: 0.9
    max_epochs: 20

optimizer:
  SGD:
    momentum: 0
    dampening: 0
    weight_decay: 0
    nesterov: False
    lr: 0.0001